name: Node.js CI [Unit tests]

on:
  pull_request:
    branches: [ master ]

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  CLIENT_ID: ${{ secrets.CLIENT_ID }}
  CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
  SOURCE_AMI: ${{ secrets.SOURCE_AMI }}
  SSH_USERNAME: ${{ secrets.SSH_USR }}

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v2
    - run: npm i    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm run build --if-present
    - run: npm test
    - run: zip -r event-rise-apis.zip *
    - run: unzip -l event-rise-apis.zip
    - run: packer fmt packer/ami.pkr.hcl
    - run: packer validate packer/ami.pkr.hcl